name: Deploy to ACR

on:
  push:
    branches:
      - main  # 指定触发构建的分支，这里假设为main分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1  # 使用Docker Buildx插件，提高构建性能和灵活性

      - name: Login to Aliyun ACR
        env:
          ACR_USER: ${{ secrets.ACR_USERNAME }}
          ACR_PASS: ${{ secrets.ACR_PASSWORD }}
        run: |
          echo "$ACR_PASS" | docker login crpi-98ymlx0yqe646pye.cn-guangzhou.personal.cr.aliyuncs.com -u "$ACR_USER" --password-stdin
          echo "ACR login successful"

      - name: Build and Push
        run: |
          docker buildx build --push --platform linux/amd64 --tag crpi-98ymlx0yqe646pye.cn-guangzhou.personal.cr.aliyuncs.com/myq-space/langrissar-jsq:latest .

      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull crpi-98ymlx0yqe646pye.cn-guangzhou.personal.cr.aliyuncs.com/myq-space/langrissar-jsq:latest
            docker stop langrissar-jsq || true
            docker rm langrissar-jsq || true
            docker run -d -p 8080:80 --name langrissar-jsq crpi-98ymlx0yqe646pye.cn-guangzhou.personal.cr.aliyuncs.com/myq-space/langrissar-jsq:latest
